pipeline {
  agent any

  environment {
    IMAGE_NAME = "springboot-devops-demo"
    IMAGE_TAG  = "${env.BUILD_NUMBER}"
  }

  options { timestamps() }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Build & Test') {
      steps {
        dir('app') {
          bat 'mvn -B clean test'
        }
      }
    }

    stage('Package') {
      steps {
        dir('app') {
          bat 'mvn -B -DskipTests package'
        }
      }
    }

    stage('Docker Build') {
      steps {
        dir('app') {
          bat "docker build -t %IMAGE_NAME%:%IMAGE_TAG% -t %IMAGE_NAME%:latest ."
        }
      }
    }

    stage('Smoke Test (Container)') {
      steps {
        dir('app') {
          bat '''
            docker rm -f %IMAGE_NAME%-ci 2>nul
            docker run -d --name %IMAGE_NAME%-ci -p 18080:8080 %IMAGE_NAME%:%IMAGE_TAG%
            timeout /t 10 /nobreak
            curl -fsS http://localhost:18080/actuator/health | findstr UP
          '''
        }
      }
      post {
        always {
          bat 'docker rm -f %IMAGE_NAME%-ci 2>nul'
        }
      }
    }
  }

  post {
    always {
      echo "Build completed: ${currentBuild.currentResult}"
    }
  }
}
